remote: [true]

experienceLevel:
 internship: [true]
 entry: [true]
 associate: [true]
 mid-senior level: [true]
 director: [false]
 executive: [false]

jobTypes:
 full-time: [true]
 contract: [true]
 part-time: [true]
 temporary: [true]
 internship: [true]
 other: [true]
 volunteer: [true]

date:
 all time: [false]
 month: [false]
 week: [false]
 24 hours: [false]

positions:
  - Product Manager
  - Product Specialist 
  - web3 analyst
  - data analyst
  - associate product Manager
  - project Manager
  - indie hacker
  - IT Support
  - Customer Support
  - Virtual assistant
  - Product Owner
  - AI/ML Engineer
  - research assistant
  - Information Systems analyst
  - AI trainer
  - Data Labeller
  - AI engineer
  - Machine learnign engineer 
  
locations:
  - Europe
  - USA
  - MENA
  - EMEA
  - APAC
  - Asia
  - Canada
  - Germany
  - Uk
  
distance: 100

company_blacklist:
  - wayfair
  - Crossover
  
titleBlacklist:
  - word1
  - word2
